# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ib_web_api
from ib_web_api.models.allocation_inner_asset_class import AllocationInnerAssetClass  # noqa: E501
from ib_web_api.rest import ApiException


class TestAllocationInnerAssetClass(unittest.TestCase):
    """AllocationInnerAssetClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllocationInnerAssetClass(self):
        """Test AllocationInnerAssetClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ib_web_api.models.allocation_inner_asset_class.AllocationInnerAssetClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
