# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ib_web_api
from ib_web_api.models.inline_response2009_scan_type_list import InlineResponse2009ScanTypeList  # noqa: E501
from ib_web_api.rest import ApiException


class TestInlineResponse2009ScanTypeList(unittest.TestCase):
    """InlineResponse2009ScanTypeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009ScanTypeList(self):
        """Test InlineResponse2009ScanTypeList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ib_web_api.models.inline_response2009_scan_type_list.InlineResponse2009ScanTypeList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
