# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ib_web_api
from ib_web_api.models.inline_response2009_locations import InlineResponse2009Locations  # noqa: E501
from ib_web_api.rest import ApiException


class TestInlineResponse2009Locations(unittest.TestCase):
    """InlineResponse2009Locations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009Locations(self):
        """Test InlineResponse2009Locations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ib_web_api.models.inline_response2009_locations.InlineResponse2009Locations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
