# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ib_web_api
from ib_web_api.models.body2 import Body2  # noqa: E501
from ib_web_api.rest import ApiException


class TestBody2(unittest.TestCase):
    """Body2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody2(self):
        """Test Body2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ib_web_api.models.body2.Body2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
